### PR TITLE
Fixes an issue with message synchronization.

### PR DESCRIPTION
**Pull request by az-raven**

### CODE REVIEW

**Review by redstonekasi — APPROVED** [review]
I completely forgot about this since the only account with "Discord" in it's name is the bot and that's ignore already but yeah, good to have. (Especially considering that Discord doesn't just yell at us, the entire bot crashes.)

**Comment by az-raven** [comment]
yeah i noticed lmao

**Comment by az-raven** [comment]
image
also, it isn't filtered
you commented it out
should I uncomment that?

**Comment by redstonekasi** [comment]
Oops, yeah do that.

**Comment by az-raven** [comment]
great!

**Pull request merged**
